### ISSUE TITLE
Site looks different

### ISSUE THREAD

**Issue by JordynD** [JordynD/use-all-the-selectors#1]
<img width="524" alt="Screen Shot 2021-03-17 at 5 06 49 PM" src="https://user-images.githubusercontent.com/77690445/111538627-4e3b4d80-8743-11eb-99b9-5bce1706a44d.png">
I have satisfied all of Markbot's requirements but my I'm getting an error message presumably because list isn't showing in colour. Please help :( 
@hellachella @carolsinc

**Comment by JordynD** [comment]
@carolsincl

**Comment by hellachella** [comment]
taking a look

**Comment by hellachella** [comment]
<img width="555" alt="Screen Shot 2021-03-18 at 10 28 03 AM" src="https://user-images.githubusercontent.com/10465921/111642700-b128f500-87d4-11eb-8d4a-0ae19f096f46.png">

"botanically" should be a different colour.


<img width="581" alt="Screen Shot 2021-03-18 at 10 28 10 AM" src="https://user-images.githubusercontent.com/10465921/111642702-b1c18b80-87d4-11eb-811e-aa6dc2637936.png">

Your list isn't highlighted.

These are the visual differences between the mockup you need to match and your assignment. I'll go see what's up with your selectors next.

**Comment by hellachella** [comment]
#### 1

```
#contents {
  color: #93a1a1;
}

#favs {
  color: #93a1a1;
}

#facts {
  color: #93a1a1;
}


#types {
  color: #93a1a1;
}
```
condense this into one rule set:
```
#contents,
#favs,
#facts,
#types {
  color: #93a1a1;
}
```
<hr>

#### 2
```
strong + .dfn {
  color: #fff;
}
```
Change to:
```
.dfn p + strong {
  color: #fff;
}
```
<hr>

#### 3
The list rules are as follows:
```
ol li:first-child {
  color: #719e47;
}

ol li:last-child {
  color: #2aa198;
}

.types li:nth-child(odd) {
  background-color: #657ba3;
}

.types li:nth-child(even) {
  background-color: #586e75;
}

.types li:nth-child(3n) {
  background-color: #d04b16;
}
```

Don't just paste this is over yours, to learn this put them in one by one and see the changes in the browser by refreshing after each.
